name: msrv

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  schedule:
    - cron: "47 5 * * 6"

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Crate
        uses: actions/checkout@v3
      - name: Checkout Toolchain
        uses: dtolnay/rust-toolchain@1.48
      - name: Running test script
        run: |
          cargo update --package log --precise=0.4.18
          cargo update --package httpdate --precise=1.0.2
          cargo update --package serde_json --precise=1.0.100
          cargo update --package chrono --precise=0.4.23
          cargo update --package num-traits --precise=0.2.18
          cargo update --package tempfile --precise=3.17.1
          cargo update --package libc --precise=0.2.163
          cargo update --package iana-time-zone --precise=0.1.61
          cargo update --package httpdate --precise=1.0.2
          cargo update --package=itoa --precise=1.0.15
          cargo update --package=ryu --precise=1.0.20
          cargo test
          cargo test --features "json-using-serde proxy punycode"
